---
title: "Mixed Models: Subjects by Stimuli random effects"
author: (Marcello Gallucci)
topic: mixed
category: example
nickname: subjects_by_stimuli
output: 
  html_document:
     includes:
         in_header: ganalytics.txt
     toc: true
     toc_float:
        collapsed: false

---


```{r echo=FALSE,results='hide'}
source("../R/functions.R")
```


`r keywords("Mixed models, hierarchical linear model, multilevel model, ANOVA, subjects by stimuli")`

`r version("0.9.7")` `r draft` `r incomplete`

# Intro 
In this example we work out analyses for a typical subjects by stimuli design using a mixed model (also called hierarchical linear model or multilevel model). We use the GAMLj module in Jamovi. To follow the examples with the software, be sure to install GAMLj module from within jamovi library. 

The design and the analyses are inspired by the discussion of _subjects by stimuli_ analyses reported in [Judd, Westfall, & Kenny, 2012](http://jakewestfall.org/publications/JWK.pdf?fbclid=IwAR2PT2AzWhJhWKIeuzJDD77OKsEi4UHuXfGy8-JppSA_U9wsdlQl7W3OdqY)

If you are not interested in the long story, you can jump to the <a href="#example-1-stimuli-crossed-with-conditions">first example right away</a>.

# The research design

Imagine an one-way repeated measures design with two conditions. Condition A and condition B. Each participant  undergoes both conditions. In each condition, a series of stimuli is presented, and for each stimulus the participant produces a response (the dependent variable). If we only consider repeated measures experimental conditions, there are two variants of this design [Baayen, Davidson, and Bates, 2008](http://www.sfs.uni-tuebingen.de/~hbaayen/publications/baayenDavidsonBates.pdf), a) one with stimuli crossed with conditions, and b) one with stimuli nested in conditions. We analyze both and we will see that from a model-building point of view, they are equivalent. That is, the way we analyze the two designs is the same.

## Examples of the design variants

### stimuli crossed with conditions

_Stimuli crossed with conditions means that the same stimuli are present in all conditions_. An example of stimuli crossed with conditions can be: A researcher investigates the effect of colors on reading words. A list of words is randomly chosen from the dictionary and it is used as the set of stimuli in the experiment. The experimental factor is color of the word presented to the participant, repeated within participants: each word is presented to the participant once in blue and once in red on the computer screen. Thus, each participant reads the all words twice, once in the blue condition and once in the red condition.  To counterbalance order effectsThis kind of design is often implemented with different orders of presentation of the conditions, making them a split-plot design. We consider this latter variant at the end of this page.

Another example can be an experiment in which the dependent variable is the response times to a instrument composed by several tasks. The instrument is proposed to the participants in two different conditions. Thus, each participants responds to the same tasks twice, once for each condition.

### stimuli nested within conditions

_Stimuli nested in conditions means that each condition feature a different set of stimuli_. In other words, the stimuli are different across conditions. Consider the previous example regarding words and colors. In this new variant two lists of words are employed: list A is presented in blue fonts and list B is presented in red fonts. The experimental factor is still color of the word presented to the participant. If the lists, for instance,  are made of 15 words each, each participant reads 30 words in total, 15 in the blue condition and 15 in the red condition. Also this kind of design can feature counterbalancing. We consider the counterbalanced variant at the end of this page.

Another example of this type of design can be a research in which participants are asked to make judgments about African American and White males, with each stimulus person described with a name and photo. In this design, the experimental conditions are the races of the stimulus persons, with the individual stimulus persons nested under condition [Judd, Westfall, & Kenny, 2012](http://jakewestfall.org/publications/JWK.pdf?fbclid=IwAR2PT2AzWhJhWKIeuzJDD77OKsEi4UHuXfGy8-JppSA_U9wsdlQl7W3OdqY). If we have, for instance, 20 photos, 10 with White stimulus persons and 10 with African American stimulus persons, the participant responds to each photo producing 20 measures of the dependent variable.

# Why the mixed model?

We all know that when we analyze repeated measures designs, we should take into the account the dependency in the data created by the repeated measures. Why? Because the scores of the dependent variable are not independent one each other (a key assumption of the between-subject ANOVA), and the dependency may bias the results. Why might there be dependency? Because in repeated measures designs each participant responds to several stimuli, making the responses more similar within participant than across participants. This, in turn, creates a correlation (dependency) among repeated measures, and this correlation should be incorporated in the statistical models to avoid (or minimize) biases. In a design with response times as dependent variable, for instance, one can observe that participants tend to be different in their average speed of response, independently to the experimental conditions. If so, some participant will be always slower than other and others faster, creating a correlation among measures.

When you have designs with multiple stimuli, the same logic applies. Responses to one stimulus may be more similar among themselves than across different stimuli, creating a correlation. A word, for instance, may be longer to read than another works, independently of the participant or the condition, thus making all the response times to it longer than for other stimuli. 

One way to capture dependency due to repetitions within participants and repetitions within stimuli is to employ a mixed model in which the model coefficients are allowed to vary across participants and across stimuli. That is, amodel with random coefficients.


# The Mixed model

The simplest mixed model that captures (some) dependency among data due to the repeated measures is a model in which the _intercepts_ vary across participants and across stimuli. In other words, the average individual differences across participants are captured by a random intercept across participants, the stimuli average differences are captured by a random intercept varying across stimuli. If we denote by $i$ each participant, and by $j$ each stimulus, $C_{ij}$ the condition variable (for simplicity with two conditions), $y_{ij}$ the dependent variable score for participant $i$ and stimulus $j$, the  model will be.

$$ \hat{y}_{ij}=a+a_{i}+a_{j}+b \cdot C_{ij}$$
where $a$ is the fixed intercept, $b$ is the fixed effect of $C$ on $y$, $a_i$ is the individual intercept associated with participant $i$, and $a_j$ is the individual intercept associated with stimulus $j$.

# Caveats

It is important to notice that the approach we are taking requires both participants and stimuli to represent _a random sample of a larger population_. For participants this is seldom a problem, because participants recruited in research are usually sampled randomly from larger populations of participants. For stimuli, however, this assumption can be tricky. A set of stimuli can be a random sample of a larger population if each individual stimulus is not interesting per se, but only because it has some charateristic shared with the population of stimuli it comes from. Under this assumption, for instance, if we use the word "beer" as a stimulus, we used it because it represents an instance of words (taken from the population of all words in the dictionary), or an instance of 4 letter words (the population would be 4 letter words), or a word indicating a liquid. Had we sampled wine, it would have been a perfectly equivalent stimulus. 

Conversely, if we are interested in the particular stimuli we chose, stimuli would not be a random sample of a larger population, and the approach described here would not be correct. For instance, if we really care about the word "beer" as a peculiar and unique stimulus, we should consider it as a level of a factor in the analysis, and not as a random case of the words sample.

Furthermore, if the stimuli are a sample of a larger population, their numerosity should be as large as possible (at least form a statistical point of view). As for participants, also for stimuli the larger the sample, the more accurate and powerful are the results.

We now turn to practical examples.


# Example 1: Stimuli crossed with conditions

One can follow the example by downloading the file [subjects by stimuli](https://github.com/mcfanda/gamlj_docs/blob/master/data/subjects_by_stimuli.csv) and open it in [jamovi](https://www.jamovi.org/download.html).

## Design
An one-way repeated measures design has two conditions:  A and B. Each participant  undergoes both conditions. In each condition, the same 30 stimuli are presented, and for each stimulus the participant produces a response (the dependent variable _y_). There are 50 participants in the sample. The following table shows how each stimulus is repeated for each condition, and it is measured 50 times per condition, where 50 is the number of participants.

`r pic("examples/mixed3/design1.png")`

The following table shows (for the first 17 participants) how each participant is measured 60 times, 30 times for each condition, where 30 is the number of stimuli per condition.

`r pic("examples/mixed3/design2.png")`

The head of the data file, in the long format, looks like this:

`r pic("examples/mixed3/data1.png")`

Which stimulus is measured in each row is indicated by the variable `stimulus`, which participant in the variable `subj`. The experimental conditions are indicated by the variable `cond`. The dependent is `y`.

## The model

We employ GAMLj mixed model module. First, we set the variables role by dropping `y` in the dependent field, `cond` in the `factors` field (i.e. categorical independent variables). Then we define the clustering variables. We have two clustering variables: `subj` and `stimuli`. We do not have to specify anything about the crossing or nesting of the classifications, the software takes care of understanding the structure of the data.

`r pic("examples/mixed3/input1.png")`

The **fixed effect** of `cond` is automatically put in the model, so we do not have to do anything here.

`r pic("examples/mixed3/input2.png")`

As regards the **random effects** we specify that we want the intercept to vary across participants (`intercept|subj`) and across stimuli (`intercept|stimuli`). For the moment, we have done setting the model up.

`r pic("examples/mixed3/input3.png")`

## Results

The first interesting table is the `Model info` table, were some info is given (for the R-squared interpretation see `r link_pages(nickname="randomcoefficients")`. 

`r pic("examples/mixed3/results1.png")`

Then we can explore the random variances. We can see that we have variance for the intercepts both across participant ($\sigma=4.55$) and across stimuli $\sigma=3.88$ and their impact is quite substantial $ICC=.312$ and $ICC=2.79$, respectively. Thus, we can say that it was a good idea to capture those portions of variances by including random intercepts varying across both participants and stimuli.

`r pic("examples/mixed3/results2.png")`


The fixed effect can now be interpreted as in any one-way ANOVA.

`r pic("examples/mixed3/results3.png")`

There is a strong effect of condition on the response to the stimuli. The direction of the effect can be evaluated with a plot.

`r pic("examples/mixed3/input4.png")`

`r pic("examples/mixed3/results4.png")`

By selecting the option `Random effects` in the plot options, we can see the random effects and how they vary across participants. Because we specified only the intercepts to be random, the random effects are all parallel, by they do show different heights, as expected by a varying intercept. 

`r pic("examples/mixed3/results5.png")`

You may have noticed that we interpreted the plot as showing the random effects across participants. We did that because GAMLj, up to the present version, does not allow to plot random effects across different clustering variables. It plots the random effects across the levels of the first clustering variable defined in the input. Thus, if we want to see the random effects across stimuli, we simply change the order of the clustering variables in the input panel, and ask for the plot again.

`r pic("examples/mixed3/input5.png")`
`r pic("examples/mixed3/results6.png")`

In the new plot, there are 30 lines representing the effect of condition for each stimulus. Again, the lines are parallel but they show different height

# Related examples
`r include_examples("mixed")`

`r issues()`