---
title: "Released Notes"
output: 
  html_document:
    includes:
         in_header: ganalytics.txt
    toc: true
    toc_float:
         collapsed: false

---

#  version 1.0.0 (future)

## Common

* contrasts labels in the simple effects parameters table
* contrasts labels in the plots
* custom levels for conditioning of continuous variables 
* labels or values in simple effects tables and plots for continuous covariates
* fix interaction disappearing from model
* fix variables name with spaces and weired characters 
* add dummy coding (0 and 1) with intercept equal to reference group
* Fix interaction symbol in windows 10

## Mixed models

* fix for models without fixed intercept
* fix for random intercept only models 
* wider range of estimation techniques when model does not converge at first run
* better warnings when model does not converge


#  version 0.9.7 (current)

* fix cluster-based centering and standardizing

#  version 0.9.6 

* Fix multinomial plot axes


#  version 0.9.4 

## New features

* Probit model
* Over-dispersed Poisson model
* Negative binomial model

## Bug fixes

* Plot without confidence intervals 
* Contrasts coding in line wiht ANOVA module

  
#  version 0.9.3 (current)


* Plotting raw data along with predicted effects

* Y-axis range can be set to the range of the dependent variable 

* Confidence intervals for all models in the plots

* Catching several errors with degenerated or non-estimable multinomial models

  

#  version 0.9.2 


* Fixed a bug in the GZLM R-squared. Now the R-squared corresponds to McFadden’s R squared [ref info](https://stats.idre.ucla.edu/other/mult-pkg/faq/general/faq-what-are-pseudo-r-squareds/)

* Fix errors with  non-standard names of variables

* Better warnings when emmeans fails to estimate the post-hocs in GZLM

* Labels in multinomial plots for separate lines variable

* Uncorrelated random effects option now works

# version 0.0.9

* First release to go public


`r issues()`
